name: Deploy HTML App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # Copy all project files to EC2
      - name: Copy app files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: "private_key.pem"
          source: "."
          target: "~/html_app"

      # SSH into EC2, install Docker if not installed, build and run container
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: "private_key.pem"
          script: |
            # Install Docker if not installed
            if ! command -v docker &> /dev/null
            then
              sudo apt-get update -y
              sudo apt-get install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker $USER
            fi

            # Navigate to app folder
            cd ~/html_app

            # Build Docker image
            docker build -t my-html-app .

            # Stop and remove old container if exists
            docker stop my-html-app || true
            docker rm my-html-app || true

            # Run new container
            docker run -d --name my-html-app -p 80:80 my-html-app:latest
